[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "WallSpeed"
dynamic = ["version"]
authors = [
    {name = "Andreas Ekstedt", email = "andreas.ekstedt@desy.de"},
    {name = "Oliver Gould", email = "oliver.gould@nottingham.ac.uk"},
    {name = "Joonas Hirvonen", email = "joonas.o.hirvonen@helsinki.fi"},
    {name = "Benoit Laurent", email = "benoit.laurent@mail.mcgill.ca"},
    {name = "Lauri Niemi", email = "lauri.b.niemi@helsinki.fi"},
    {name = "Philipp Schicho", email = "schicho@itp.uni-frankfurt.de"},
    {name = "Tuomas Tenkanen", email = "tuomas.tenkanen@su.se"},
    {name = "Jorinde van de Vis", email = "j.m.vandevis@uu.nl"},
]
description = "A package for computing the bubble wall speed"
license = {text = "MIT"}
classifiers = [
    "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">=3.7"
dependencies = [
    "cosmoTransitions>=2.0.6",
    "findiff>=0.9.2",
    "h5py>=3.8.0",
    "matplotlib>=3.5.1",
    "numpy>=1.21.5",
    "pytest>=7.2.2",
    "scipy>=1.8.0",
]
readme = "README.rst"

[project.urls]
"Homepage" = "https://wallspeed.readthedocs.io/"
"Repository" = "https://github.com/jorindevandevis/WallSpeed"
