name: WallGo main documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install docs dependencies
        run: |
          pip install .[docs]

      - name: Sphinx build
        run: |
          cd ${{ github.workspace }}
          cd docsrc
          make html
          mkdir ../docs
          mv _build/html/* ../docs
          echo "The HTML pages have been moved to docs."
          cd ..
          pwd
          ls -l docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true