name: Publish to PyPI

on:
  release:
    types: [published]
  pull_request:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/WallGo/
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
      
    - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
